[workspace]
members = [
    "litho-cli",
    "litho-compiler",
    "litho-diagnostics",
    "litho-import",
    "litho-language",
    "litho-lsp",
    "litho-lsp-wasm",
    "litho-tests",
    "litho-types",
	"litho-validation",
]
