[workspace]
members = [
    "litho-cli",
    "litho-codegen",
    "litho-compiler",
    "litho-diagnostics",
    "litho-import",
    "litho-language",
    "litho-lsp",
    "litho-lsp-wasm",
    "litho-tests",
    "litho-types",
    "litho-validation",
    "wrom-derive",
]
resolver = "2"

[profile.bench]
opt-level = 3
lto = true
