[package]
name = "litho-language"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version = "1.3.2", features = ["derive"] }
ariadne = "0.1.5"
logos = "0.12.1"
nom = "7.1.1"
serde_json = "1.0.91"
unindent = "0.1.10"

litho-diagnostics = { path = "../litho-diagnostics" }
wrom = { path = "../wrom" }
wrom-derive = { path = "../wrom-derive" }

[dev-dependencies]
async-graphql-parser = "7.0.11"
graphql-parser = "0.4.0"
