[package]
name = "copa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
chrono = "0.4.21"
futures = "0.3.21"
