[package]
name = "kono-schema"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql-parser = "0.4.0"
heck = "0.4.0"

[dev-dependencies]
unindent = "0.1.10"
