[package]
name = "kono-executor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.0"
graphql-parser = "0.4.0"
indexmap = "1.9.1"
serde_json = { version = "1.0.82" }
